services:
  main:
    build: .
    env_file:
      - .env
    container_name:
      ${PYTHON_CONTAINER_NAME}
    ports:
      - '${PYTHON_PORT_OUTER}:${PYTHON_PORT}'
    stdin_open: true
    tty: true

  db:
    image: postgres:18.1
    env_file:
      - .env
    container_name:
      ${POSTGRES_CONTAINER_NAME}
    restart: always
    shm_size: 128mb
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/18/main/
    ports:
      - '${POSTGRES_PORT_OUTER}:${POSTGRES_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:8.2
    env_file:
      .env
    container_name:
      ${REDIS_CONTAINER_NAME}
    restart: always
    command: ['redis-server', '--appendonly', 'no', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - '${REDIS_PORT_OUTER}:${REDIS_PORT}'